### ISSUE TITLE
Proposal: v0.3 is compatible with `biomass` version 0.7.0 or more

### ISSUE THREAD

**Issue by himoto** [pasmopy/pasmopy#77]
**Correspondence table:**
| [`biomass`](https://github.com/biomass-dev/biomass) |  `pasmopy`  |
| --- | --- |
| 0.5.2 - 0.5.5 | 0.1.x |
| 0.6.0 - 0.6.2 | 0.2.x |
| 0.7.0+ | 0.3.x |

**TODO:**

- [x] Bump minimal biomass version in `requirements.txt`
- [x] Update `template` in `pasmopy/construction`
- [x] Update `docs/modules`
- [x] Fix example in `individualization.py`
- [x] Fix `tests/test_fos_model.py`
